# Generated by Django 3.0.2 on 2020-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_task',
            field=models.BooleanField(default=False, verbose_name='Done task'),
        ),
    ]
