# Generated by Django 3.0.2 on 2020-02-01 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200129_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_task',
            field=models.BooleanField(default=False, verbose_name='done task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='due date'),
        ),
    ]
